server:
  port: 0

spring:
  application:
    name: article-service #服务名称

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC
    username: root
    password: 2005


  data:
    redis:
      password:
      port: 6379
      host: 127.0.0.1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    com.baomidou.mybatisplus: DEBUG
    org.mybatis.spring: DEBUG
    org.apache.ibatis: DEBUG
