server:
  port: 0


spring:
  application:
    name: message-service
  #profiles:
  # active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC
    username: root
    password: 2005
  data:
    redis:
      password:
      port: 6379
      host: 127.0.0.1



  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: 2897924003@qq.com
    password: ldqqcsrbgkufdgfe
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  rabbitmq:
    username: guest
    host: localhost
    password: guest
    port: 5672
    virtual-host: /








